site_name: Hovercode Python SDK
site_url: https://hovercode.com/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            heading_level: 2
            show_source: false
            show_signature_annotations: true
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting started:
      - Overview: getting-started/index.md
      - Installation: getting-started/installation.md
      - Authentication: getting-started/authentication.md
      - Quickstart: getting-started/quickstart.md
  - Guides:
      - Overview: guides/index.md
      - Examples: guides/examples.md
      - Troubleshooting: guides/troubleshooting.md
  - API:
      - Overview: api/index.md
      - Hovercodes: api/hovercodes.md
  - Reference:
      - Overview: reference/index.md
      - Data types: reference/data-types.md
      - Exceptions: reference/exceptions.md
      - Changelog: reference/changelog.md

